tid_rapport/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from .views import (
    IndexView,
    ProjektList,
    ProjektDetail,
    CreateProjekt,
    ProjektUpdate,
    ProjektDelete,
    TidDetail,
    tidlist,
    CreateTid,
    TidUpdate,
    TidDelete,
    tidsedel,
)

app_name = "tid_rapport"

urlpatterns = [
    path("start/", login_required(IndexView.as_view()), name="index"),
    # Projekt
    path("projekt/list/", login_required(ProjektList.as_view()), name="projekt_list"),
    path(
        "projekt/<int:pk>/",
        login_required(ProjektDetail.as_view()),
        name="projekt_detail",
    ),
    path(
        "projekt/create/",
        login_required(CreateProjekt.as_view()),
        name="projekt_create",
    ),
    path(
        "projekt/<int:pk>/update/",
        login_required(ProjektUpdate.as_view()),
        name="projekt_update",
    ),
    path(
        "projekt/<int:pk>/delete/",
        login_required(ProjektDelete.as_view()),
        name="projekt_delete",
    ),
    # Tid
    path("tid/list/", tidlist, name="tid_list"),
    path("tid/<int:pk>/", login_required(TidDetail.as_view()), name="tid_detail"),
    path("tid/create/", login_required(CreateTid.as_view()), name="tid_create"),
    path(
        "tid/<int:pk>/update/", login_required(TidUpdate.as_view()), name="tid_update"
    ),
    path(
        "tid/<int:pk>/delete/", login_required(TidDelete.as_view()), name="tid_delete"
    ),
    path("tidsedel/", tidsedel, name="tidsedel"),
]

tidtest/urls.py
from django.urls import path, include
from django.contrib import admin
from django.contrib.auth import views as auth_views
from users import views as user_views


urlpatterns = [
    path('', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('profil', user_views.profiles, name='profil'),
    path('', include('tid_rapport.urls', namespace='tid_rapport')),
    path('admin/', admin.site.urls, name='admin')
]

tid_rapport/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from django_currentuser.db.models import CurrentUserField


class Projekt(models.Model):
    class Meta:
        verbose_name_plural = "Projekt"
        ordering = ["projektnr"]

    projektnr = models.CharField(max_length=100, verbose_name="Projektnummer", blank=True)
    anlaggning = models.CharField(max_length=100, verbose_name="Anläggning", blank=True)
    kund = models.CharField(max_length=100, verbose_name="Kund", blank=True)
    ort = models.CharField(max_length=100, verbose_name="Ort", blank=True)

    def __str__(self):
        return str(self.projektnr)

    def get_absolute_url(self):
        return reverse("tid_rapport:projekt_detail", kwargs={"pk": self.pk})


class Tid(models.Model):
    class Meta:
        verbose_name_plural = "Tider"
        ordering = ["-ar", "-vecka"]

    user = CurrentUserField()
    ar = models.IntegerField(default=2019, verbose_name="År")
    vecka = models.IntegerField(default=1, verbose_name="Vecka")
    projektnr = models.ForeignKey(
        "Projekt", on_delete=models.CASCADE, verbose_name="Projekt"
    )
    mon = models.FloatField(default=0, verbose_name="Måndag")
    tis = models.FloatField(default=0, verbose_name="Tisdag")
    ons = models.FloatField(default=0, verbose_name="Onsdag")
    tors = models.FloatField(default=0, verbose_name="Torsdag")
    fre = models.FloatField(default=0, verbose_name="Fredaq")
    lor = models.FloatField(default=0, verbose_name="Lördag")
    son = models.FloatField(default=0, verbose_name="Söndag")
    restid = models.FloatField(default=0, verbose_name="Restid")
    trakt = models.IntegerField(default=0, verbose_name="Trakt")
    pmil = models.IntegerField(default=0, verbose_name="Mil egen bil")
    fmil = models.IntegerField(default=0, verbose_name="Mil firmabil bil")

    def __str__(self):
        return str(self.vecka)

    def get_tot(self):
        tot = (
            self.mon
            + self.tis
            + self.ons
            + self.tors
            + self.fre
            + self.lor
            + self.son
            + self.restid
        )
        return tot

    def get_full_name(self):
        return self.user.first_name + " " + self.user.last_name

    def get_absolute_url(self):
        return reverse("tid_rapport:tid_detail", kwargs={"pk": self.pk})

tid_rapport/forms.py
from django import forms

from .models import Projekt, Tid


class ProjektForm(forms.ModelForm):
    class Meta:
        model = Projekt
        fields = ("projektnr", "anlaggning", "ort", "kund")


class TidForm(forms.ModelForm):
    class Meta:
        model = Tid
        fields = (
            "ar",
            "vecka",
            "projektnr",
            "mon",
            "tis",
            "ons",
            "tors",
            "fre",
            "lor",
            "son",
            "restid",
            "trakt",
            "pmil",
            "fmil",
        )


class TidSedelForm(forms.Form):
    ar = forms.IntegerField(initial=2019)
    start_vecka = forms.IntegerField()
    stopp_vecka = forms.IntegerField()

tid_rapport/views.py
from django.views.generic import (
    TemplateView,
    ListView,
    CreateView,
    UpdateView,
    DeleteView,
    DetailView,
)
from django.http.response import HttpResponse
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.urls import reverse_lazy
from .models import Projekt, Tid
from .forms import ProjektForm, TidForm, TidSedelForm
from tid_rapport.tidsedel import skapa_tidsedel
from django_currentuser.middleware import get_current_authenticated_user


class IndexView(TemplateView):
    template_name = "index.html"


# Projekt
class ProjektList(ListView):
    template_name = "projekt/projekt_list.html"
    model = Projekt
    context_object_name = "projekt"


class ProjektDetail(DetailView):
    template_name = "projekt/projekt_detail.html"
    model = Projekt


class CreateProjekt(CreateView):
    template_name = "projekt/projekt_form.html"
    model = Projekt
    form_class = ProjektForm
    success_url = reverse_lazy("tid_rapport:projekt_list")


class ProjektUpdate(UpdateView):
    template_name = "projekt/projekt_form.html"
    model = Projekt
    form_class = ProjektForm
    success_url = reverse_lazy("tid_rapport:projekt_list")


class ProjektDelete(DeleteView):
    template_name = "projekt/projekt_confirm_delete.html"
    model = Projekt
    success_url = reverse_lazy("tid_rapport:projekt_list")


# Tid
@login_required
def tidlist(request):

    user = get_current_authenticated_user()
    tider = Tid.objects.filter(user=user)

    return render(request, "tid/tid_list.html", {"tider": tider})


class TidDetail(DetailView):
    template_name = "tid/tid_detail.html"
    model = Tid


class CreateTid(CreateView):
    template_name = "tid/tid_form.html"
    model = Tid
    form_class = TidForm
    success_url = reverse_lazy("tid_rapport:tid_list")


class TidUpdate(UpdateView):
    template_name = "tid/tid_form.html"
    model = Tid
    form_class = TidForm
    success_url = reverse_lazy("tid_rapport:tid_list")


class TidDelete(DeleteView):
    template_name = "tid/tid_confirm_delete.html"
    model = Tid
    success_url = reverse_lazy("tid_rapport:tid_list")


@login_required
def tidsedel(request):

    if request.method == "POST":

        form = TidSedelForm(request.POST)

        if form.is_valid():
            ar = form.cleaned_data["ar"]
            start = form.cleaned_data["start_vecka"]
            stopp = form.cleaned_data["stopp_vecka"]

            if start == stopp:
                filepath = "Tidsedel" + str(ar) + "V" + str(start) + ".xlsx"
            else:
                filepath = (
                    "Tidsedel" + str(ar) + "V" + str(start) + "-" + str(stopp) + ".xlsx"
                )
            response = HttpResponse(
                content_type="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
            )
            response["Content-Disposition"] = "attachment; filename=" + filepath
            user = get_current_authenticated_user()

            return skapa_tidsedel(ar, start, stopp, response, user)

    else:
        form = TidSedelForm()

    return render(request, "tidsedel.html", {"form": form})

users/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required


@login_required
def profiles(request):

    return render(request, template_name='users/profil.html')

templates/base.html
<!doctype html>
{% load staticfiles %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <title>Cards</title>
  </head>
  <body class="bg-light">
    <!-- Start navbar! -->
    <nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark">
      <a class="navbar-brand text-warning" href="{% url 'admin:index' %}">Admin</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">

          <li class="nav-item">
            <a class="nav-link text-warning" href="{% url 'tid_rapport:tid_list' %}">Tidrapport</a>
          </li>

          <li class="nav-item">
            <a class="nav-link text-warning" href="{% url 'tid_rapport:kund_list' %}">Kund</a>
          </li>

          <li class="nav-item">
            <a class="nav-link text-warning" href="{% url 'tid_rapport:projekt_list' %}">Projekt</a>
          </li>

          <li class="nav-item">
            <a class="nav-link text-warning" href="{% url 'tid_rapport:arbetsplats_list' %}">Arbetsplats</a>
          </li>
        </ul>
        <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="email" placeholder="Email" aria-label="Email">
          <input class="form-control mr-sm-2" type="password" placeholder="Password" aria-label="Password">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Log in</button>
        </form>
      </div>
    </nav>
    <!-- End navbar! -->
  <br>
    {% block body_block %}

    {% endblock %}
      <!-- Optional JavaScript -->


    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
  </body>
</html>

templates/index.html
{% extends 'base.html' %}
    {% block body_block %}
    <div class="container">
      <div class="card bg-dark text-warning mt-5 shadow">
        <div class="card-body">

        </div>
      </div>
    </div>
    {% endblock %}

templates/tid.html
{% extends 'base.html' %}
    {% block body_block %}
        <!-- Start Card Content 5-->
    <div class="container">
      <div class="card bg-dark text-warning mt-5 shadow">
        <div class="card-body">
          <h2 class="card-title">Projekt visa</h2>
          <table class="table table-hover">
            <thead class="thead-dark">
              <tr>
                <th scope="col">#</th>
                <th scope="col">Datum</th>
                <th scope="col">Projektnr</th>
                <th scope="col">Timmar</th>
                <th scope="col">Arbetsplats</th>
                <th scope="col">Kund</th>
              </tr>
            </thead>
            <tbody>
                {% for tid in object_list %}
                    <tr>
                        <th scope="row">{{ forloop.counter }}</th>
                        <td>{{ tid.datum }}</td>
                        <td>{{ tid.projektnr }}</td>
                        <td>{{ tid.timmar }}</td>
                        <td>{{ tid.arbetsplats }}</td>
                        <td>{{ tid.kund }}</td>
                    </tr>
                {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>
    <!-- End Card Content 5-->
    {% endblock %}

tid_rapport/templates/base.html
<!doctype html>
{% load staticfiles %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="{% static 'tid_rapport/css/style.css' %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.1/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <title>{% block title %}{% endblock %}</title>
  </head>
  <body>
    <!-- Start navbar! -->
    <nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark">
      {% if user.is_authenticated %}
        <a class="navbar-brand text-warning" href="{% url 'tid_rapport:index' %}">Home</a>
      {% endif %}
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        {% if user.is_authenticated %}
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link text-warning" href="{% url 'tid_rapport:tid_list' %}">Tid</a>
          </li>
          <li class="nav-item">
            <a class="nav-link text-warning" href="{% url 'tid_rapport:projekt_list' %}">Projekt</a>
          </li>
          <li class="nav-item">
            <a class="nav-link text-warning" href="{% url 'tid_rapport:tidsedel' %}">Tidsedel</a>
          </li>
        </ul>
        <a class="btn btn-outline-danger my-2 my-sm-0" href="{% url 'logout' %}">Logga ut</a>
        {% endif %}
      </div>
    </nav>
    <!-- End navbar! -->
  <br>
  <div class="container">
      <div class="card bg-dark mt-5 text-warning shadow">
        <div class="card-body">
            {% block body_block %}

            {% endblock %}
        </div>
      </div>
  </div>
    <!-- Optional JavaScript -->


    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
  </body>
</html>

tid_rapport/templates/index.html
{% extends 'base.html' %}
    {% block body_block %}
        <h1 class="card-title">Välkommen</h1>
            <a class="btn btn-outline-success btn-lg btn-block" href="{% url 'tid_rapport:tid_list' %}" role="button">Tid</a>
            <a class="btn btn-outline-success btn-lg btn-block" href="{% url 'tid_rapport:projekt_list' %}" role="button">Projekt</a>
            <a class="btn btn-outline-success btn-lg btn-block" href="{% url 'tid_rapport:tidsedel' %}" role="button">Tidsedel</a>
            <a class="btn btn-outline-success btn-lg btn-block" href="{% url 'profil' %}" role="button">Användarprofil</a>
    {% endblock %}

tid_rapport/templates/projekt/projekt_confirm_delete.html
{% extends 'base.html' %}
{% block title %}Projekt{% endblock %}
{% block body_block %}
    <form method="post">{% csrf_token %}
        <h3 class="card-title">Är du säker på att du vill radera ?</h3>
        <p class="card-text">Projekt {{ object }}</p>
        <input class="btn btn-outline-danger" type="submit" value="Confirm">
    </form>
{% endblock %}

tid_rapport/templates/projekt/projekt_detail.html
{% extends 'base.html' %}
    {% block title %}Projekt{% endblock %}
    {% block body_block %}
        <h3 class="card-title">Projektnummer: {{ object.projektnr }}</h3>
        <p>Anläggning: {{ object.anlaggning }}</p>
        <p>Ort: {{ object.ort }}</p>
        <p>Kund: {{ object.kund }}</p>
    {% endblock %}

tid_rapport/templates/projekt/projekt_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}Projekt{% endblock %}
{% block body_block %}
    <form method="post">{% csrf_token %}
        {{ form|crispy }}
        <input class="btn btn-outline-success" type="submit" value="Spara">
    </form>
{% endblock %}

tid_rapport/templates/projekt/projekt_list.html
{% extends 'base.html' %}
    {% block title %}Projekt{% endblock %}
    {% block body_block %}
        <h2 class="card-title" ></h2>
        <table class="table table-hover">
            <thead class="thead-dark">
                <tr>
                    <th class="text-warning" scope="col">#</th>
                    <th class="text-warning" scope="col">Projektnummer</th>
                    <th class="text-warning" scope="col"></th>
                </tr>
            </thead>
            <tbody>
                {% for p in projekt %}
                    <tr>
                        <th scope="col">{{ forloop.counter }}</th>
                        <td><a href="{{ p.get_absolute_url }}">{{ p.projektnr }}, {{ p.anlaggning}}</a></td>
                        <td><a class="text-success" href="{{ p.get_absolute_url }}update/"><i class="fas fa-edit"></i></a>
                            <a class="text-danger" href="{{ p.get_absolute_url }}delete/"><i class="fas fa-trash-alt"></i></a>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        <a class="btn btn-outline-warning" href="{% url 'tid_rapport:projekt_create' %}">Skapa ny</a>
    {% endblock %}

tid_rapport/templates/tid/tid_confirm_delete.html
{% extends 'base.html' %}
{% block title %}Tid{% endblock %}
{% block body_block %}
    <form method="post">{% csrf_token %}
        <h3 class="card-title">Är du säker på att du vill radera ?</h3>
        <p class="card-text">Vecka: {{ object }}</p>
        <input class="btn btn-outline-danger" type="submit" value="Confirm">
    </form>
{% endblock %}

tid_rapport/templates/tid/tid_detail.html
{% extends 'base.html' %}
    {% block title %}Tid{% endblock %}
    {% block body_block %}
        <h3 class="card-title">År:{{ object.ar }}   Vecka: {{ object.vecka }}</h3>
        <p class="card-text">Projekt: {{ object.projektnr }}, {{ object.projektnr.anlaggning }}</p>
        <p class="card-text">Måndag: {{ object.mon }}</p>
        <p class="card-text">Tisdag: {{ object.tis }}</p>
        <p class="card-text">Onsdag: {{ object.ons }}</p>
        <p class="card-text">Torsdag: {{ object.tors }}</p>
        <p class="card-text">Fredag: {{ object.fre }}</p>
        <p class="card-text">Lördag: {{ object.lor }}</p>
        <p class="card-text">Söndag: {{ object.son }}</p>
        <p class="card-text">Restid: {{ object.restid }}</p>
        <p class="card-text">Trakt: {{ object.trakt }}</p>
    {% endblock %}

tid_rapport/templates/tid/tid_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}Tid{% endblock %}
{% block body_block %}
    <form method="post">{% csrf_token %}
        {{ form|crispy }}
        <input class="btn btn-outline-success" type="submit" value="Spara">
    </form>
{% endblock %}

tid_rapport/templates/tid/tid_list.html
{% extends 'base.html' %}
    {% block title %}Tid{% endblock %}
    {% block body_block %}
        <h2 class="card-title" >Tid</h2>
        <table class="table table-hover">
            <thead class="thead-dark">
                <tr>
                    <th class="text-warning" scope="col">Vecka</th>
                    <th class="text-warning" scope="col">Beskrivning</th>
                    <th class="text-warning" scope="col">Totalt</th>
                    <th class="text-warning" scope="col"></th>
                </tr>
            </thead>
            <tbody>
                    {% for tid in tider %}
                    <tr>
                        <td><a href="{{ tid.get_absolute_url }}">{{ tid.ar }} v.{{ tid.vecka }}</a></td>
                        <td>{{ tid.projektnr }}, {{ tid.projektnr.anlaggning }}</td>
                        <td>
                            {{ tid.get_tot }} Tim
                        </td>
                        <td>
                            <a class="text-success" href="{{ tid.get_absolute_url }}update/"><i class="fas fa-edit"></i></a>
                            <a class="text-danger" href="{{ tid.get_absolute_url }}delete/"><i class="fas fa-trash-alt"></i></a>
                        </td>
                    </tr>
                    {% endfor %}
            </tbody>
        </table>
        <a class="btn btn-outline-warning" href="{% url 'tid_rapport:tid_create' %}">Skapa ny</a>
    {% endblock %}

tid_rapport/templates/tidsedel.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
    {% block title %}Tidsedel{% endblock %}
    {% block body_block %}
        <h2 class="card-title">Skapa tidsedel</h2>
        <form method="post">{% csrf_token %}
            {{ form|crispy }}
            <input class="btn btn-outline-warning" type="submit" value="Skapa tidsedel">
        </form>
    {% endblock %}

users/templates/users/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}Logga in{% endblock %}
{% block body_block %}
    <h2 class="card-title">Logga in</h2>
    <form method="post">{% csrf_token %}
        {{ form|crispy }}
        <br>
        <input class="mt-2 btn btn-outline-success" type="submit" value="Logga in">
    </form>
{% endblock %}

users/templates/users/logout.html
{% extends 'base.html' %}
{% block title %}Logga ut{% endblock %}
{% block body_block %}
    <h1 class="card-title">Utloggad</h1>
    <a href="{% url 'login' %}">Logga in</a>
{% endblock %}

users/templates/users/profil.html
{% extends 'base.html' %}
{% block title %}Profil{% endblock %}
{% block body_block %}
    <h1 class="card-title">Användarprofil</h1>
    <p>Användar namn: {{ user.username }}</p>
    <p>Förnamn: {{ user.first_name }}</p>
    <p>Efternamn: {{ user.last_name }}</p>
    <p>Email: {{ user.email }}</p>
{% endblock %}